---
jenkins:
  systemMessage: "Devops Jenkins as Code (JaC)"

  numExecutors: 5
  scmCheckoutRetryCount: 2
  mode: NORMAL
  globalNodeProperties:
    - envVars:
        env:
          - key: FOO
            value: BAR
  views:
    - myView:
        name: "Devops Jobs Config as Code"
  securityRealm:
    ldap:
      configurations:
        - server: "ldaps://ldap.jumpcloud.com"
          rootDN: ""
          inhibitInferRootDN: true
          userSearchBase: "ou=Users,o=5ec1612e063bfb140233c749,dc=jumpcloud,dc=com"
          userSearch: "uid={0}"
          groupSearchBase: "ou=Users,o=5ec1612e063bfb140233c749,dc=jumpcloud,dc=com"
          groupSearchFilter: "(& (cn={0})(objectclass=groupOfNames))"
          groupMembershipStrategy:
            fromGroupSearch:
              filter: "(member={0})"
          managerDN: "uid=myldapuser,ou=Users,o=5ec1612e063bfb140233c749,dc=jumpcloud,dc=com"
          managerPasswordSecret: "Test1234"
          displayNameAttributeName: "cn"
          mailAddressAttributeName: "mail"
      cache:
        size: 100
        ttl: 10
      userIdStrategy: "caseInsensitive"
      groupIdStrategy: "caseInsensitive"
  authorizationStrategy:
    roleBased:
      roles:
        global:
          - name: "admin"
            description: "Jenkins administrators"
            permissions:
              - "Overall/Administer"
            assignments:
              - "jena"
          - name: "readonly"
            description: "Read-only users"
            permissions:
              - "Overall/Read"
              - "Job/Read"
            assignments:
              - "authenticated"           
  clouds:
    - docker:
        name: "docker"
        dockerApi:
          dockerHost:
            uri: "unix:///var/run/docker.sock"
        templates:
          - labelString: "docker-agent"
            dockerTemplateBase:
              image: "jenkins/slave"
              volumes:
                - hello:/hello
                - world:/world
              environmentsString: |
                hello=world
                foo=bar
            remoteFs: "/home/jenkins/agent"
            connector:
              attach:
                user: "jenkins"
            instanceCapStr: "10"            
tool:
  git:
    installations:
      - name: git
        home: /usr/local/bin/git
security: 
  globalJobDslSecurityConfiguration: 
    useScriptSecurity: false 
jobs:
  - script: >
      freeStyleJob("Jobs Generator") {
        scm {
            github('imanol-dev/jenkins_as_code_jobs', 'master')
        }
        steps {
            dsl {
              external('*.groovy')
            }
        }
      }

unclassified:
  jiraGlobalConfiguration:
    sites:
      - url: "https://issues.jenkins-ci.org"
  mailer:
    replyToAddress: "do-not-reply@acme.org"
    smtpHost: "smtp.acme.org"
    smtpPort: 4441
  bitbucketendpointconfiguration:
    endpoints:
    - bitbucketServerEndpoint:
        displayName: "gobitbucket"
        serverUrl: "http://10.0.2.199"        
        callCanMerge: true
        manageHooks: true
        credentialsId: "mycreds"
        

        